default:
  image:
    name: docker-public.binary.picodata.io/kaniko-project/executor:v1.20.1-debug
    entrypoint: ['']
    pull_policy: [if-not-present]
  tags:
    - docker-k8s

variables:
    GIT_DEPTH: 1
    DOCKER_REGISTRY_PUB: docker-public.binary.picodata.io
    DOCKER_AUTH_CONFIG: $DOCKER_AUTH_RW
  # k8s runner config
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_REQUEST: "4Gi"

stages:
  - build


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

.kaniko-image:
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ${DOCKERFILE}
      --build-arg TARANTOOL_VERSION=$TAG_LONG ${PUSH_DOCKER}
      --cache=false --cache-run-layers=true --single-snapshot --compressed-caching=false --use-new-run --snapshot-mode=redo --cleanup
      --destination $DOCKER_REGISTRY_PUB/backup-picodata:latest

build-backup:
  stage: build
  extends: .kaniko-image
  only:
    changes:
      - $DOCKERFILE
      - backup/picobackup.sh
  variables:
    DOCKERFILE: backup/Dockerfile

