default:
  image:
    name: docker-proxy.binary.picodata.io/alpine/helm:3.16
    pull_policy: [if-not-present]
  tags:
    - docker

variables:
    GIT_DEPTH: 1
    DOCKER_REGISTRY_PUB: docker-public.binary.picodata.io
    DOCKER_AUTH_CONFIG: $DOCKER_AUTH_RW
  # k8s runner config
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_REQUEST: "4Gi"

stages:
  - build


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

.helm:
  before_script:
    - mkdir -p ~/.docker/
    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
  script:
    - helm package picodata/
    - version=$(helm show chart picodata/ | grep version | awk '{print $2}')
    - helm push picodata-${version}.tgz oci://$DOCKER_REGISTRY_PUB/helm

public-helm-chart:
  stage: build
  extends: .helm
  rules:
    - if: $CI_COMMIT_TAG
