---
apiVersion: v1
kind: Pod
metadata:
  name: picodata-restore
  namespace: picodata
spec:
  containers:
    - name: picodata-restore
      image: docker.binary.picodata.io/ubuntu:22.04
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 5; done"]
      volumeMounts:
        - name: picodata-pico-0
          mountPath: /pico
  volumes:
    - name: picodata-pico-0
      persistentVolumeClaim:
        claimName: picodata-pico-0
