apiVersion: v1
kind: Secret
metadata:
  name: picodata-s3
  namespace: picodata
type: Opaque  
stringData:
  aws_access_key_id: ref+vault://infra/gitlab#s3_AccessKey
  aws_secret_access_key: ref+vault://infra/gitlab#s3_SecretKey