apiVersion: v1
kind: Secret
metadata:
  name: picodata-s3
  namespace: picodata
type: Opaque  
stringData:
  accessKeyID: ref+vault://infra/gitlab#s3_AccessKey
  secretAccessKey: ref+vault://infra/gitlab#s3_SecretKey
  endpoint: https://storage.yandexcloud.net
  region: ru-central1