{{- if .Values.picodata.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-{{ $.Release.Namespace | default "default" }}
  namespace: {{ $.Release.Namespace | default "default" }}
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup-picodata
            image: docker.binary.picodata.io/backup-picodata:latest
            env:
            - name: BACKUP_PATH
              value: {{ .Values.picodata.dataDir }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom: 
                secretKeyRef:
                  name: picodata-s3
                  key: accessKeyID  
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: picodata-s3
                  key: secretAccessKey
            - name: S3_BUCKET
              value: {{ .Values.picodata.backup.backet }}      
            volumeMounts:
            - mountPath: {{ .Values.picodata.dataDir }}
              name: backup-{{ include "picodata.fullname" . }}
          volumes:
          - name: backup-{{ include "picodata.fullname" . }}
            persistentVolumeClaim:
              claimName: {{ include "picodata.fullname" . }}-picodata-0           
{{- end }}