{{- range $tier, $tier_map :=  $.Values.picodata.tiers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $tier_map.tierName }}-{{ include "picodata.fullname" $ }}
  namespace: {{ $.Release.Namespace | default "default" }}
data:
  config.yaml: |
      cluster:
        name: {{ $.Values.clusterName }}
        tier:
          {{ $tier_map.tierName }}:
            replication_factor: {{ $tier_map.replicationFactor }}
            can_vote: {{ $tier_map.canVote }}
        default_replication_factor: {{ $.Values.picodata.default_replication_factor }}
        default_bucket_count: {{ $.Values.picodata.default_bucket_count }}
        shredding: {{ $.Values.picodata.shredding }}
      instance:
        instance_dir: {{ $.Values.picodata.instanceDir }}
        tier: {{ $tier_map.tierName }}
        peer:
        {{- with (first $.Values.picodata.tiers) }}
        - {{ .tierName }}-{{ include "picodata.fullname" $ }}-0.{{ .tierName }}-{{ include "picodata.fullname" $ }}-interconnect.{{ $.Release.Namespace }}.svc.cluster.local:{{ include "picodata.binaryTargetPort" $ }}
        {{- end }}
        http_listen: 0.0.0.0:{{ include "picodata.httpTargetPort" $ }}
        admin_socket: {{ $.Values.picodata.instanceDir }}/admin.sock
        plugin_dir: /var/lib/plugins
        audit: {{ $tier_map.audit | default "null" }}
        log:
          level: {{ $tier_map.log.level }}
          destination: {{ $tier_map.log.destination }}
          format: {{ $tier_map.log.format }}
        memtx:
          memory: {{ $tier_map.memtx.memory }}
        vinyl:
          memory: {{ $tier_map.vinyl.memory }}
          cache: {{ $tier_map.vinyl.cache }}
        pg:
    {{- if $tier_map.pg.expose }}
          listen: 0.0.0.0:{{ include "picodata.psqlTargetPort" $ }}
    {{- else }}
          listen: 127.0.0.1:{{ include "picodata.psqlTargetPort" $ }}
    {{- end }}
          ssl: {{ $tier_map.pg.ssl }}
      {{- end }}
