{{- range $tier, $tier_map :=  $.Values.picodata.tiers }}
{{- if $tier_map.ingress.enabled -}}
{{- $svcPort := include "picodata.httpTargetPort" $ -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $tier_map.tierName }}-{{ include "picodata.fullname" $ }}
  namespace: {{ $.Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ $tier_map.tierName }}-{{ include "picodata.fullname" $ }}
    app.kubernetes.io/cluster: {{ $.Values.clusterName }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  {{- with $tier_map.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $tier_map.ingress.className }}
  {{- if $tier_map.ingress.tls }}
  tls:
    {{- range $tier_map.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $tier_map.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $tier_map.tierName }}-{{ include "picodata.fullname" $ }}-ext
                port:
                  number: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}