{{- if .Values.picodata.ingress.enabled -}}
{{- $svcPort := include "picodata.httpTargetPort" . -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "picodata.fullname" . }}-ext-ingress
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ include "picodata.fullname" . }}-ext-ingress
    app.kubernetes.io/cluster: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.picodata.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.picodata.ingress.className }}
  {{- if .Values.picodata.ingress.tls }}
  tls:
    {{- range .Values.picodata.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.picodata.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "picodata.fullname" $ }}-interconnect
                port:
                  number: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
