apiVersion: v1
kind: Service
metadata:
  name: {{ include "picodata.fullname" . }}-ext
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ include "picodata.fullname" . }}-ext
    app.kubernetes.io/cluster: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.router.service.type }}
  ports:
    {{- toYaml .Values.router.service.ports | nindent 4 }}
  selector: 
    app.kubernetes.io/name: {{ include "picodata.fullname" . }}-router
